### ISSUE TITLE
Unknown formats

### ISSUE THREAD

**Issue by tlienart** [Arkoniak/UrlDownload.jl#21]
Some of the UCI datasets have `.data` extension e.g.

http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

could I somehow indicate that this should be treated as CSV?

**Comment by Arkoniak** [comment]
Yes, you can

```julia
using UrlDownload
using DataFrames
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

df = urldownload(url, true, format=:CSV) |> DataFrame
```

**Comment by tlienart** [comment]
awesome, thank you
