### ISSUE TITLE
compressed versions

### ISSUE THREAD

**Issue by tbeason** [Arkoniak/UrlDownload.jl#9]
This package looks really promising! One case that I encounter often is a compressed `.csv` file (a `.zip` or `.gz` with a single `.csv` inside). It is easy to still stream these files into a `DataFrame`, but it requires the intermediate step of passing the stream through `ZipFile.jl` or `CodecZLib.jl`. Do you think you could add something like this?

Or, alternatively, do you have plans to allow custom parsers?

**Comment by Arkoniak** [comment]
That's an interesting proposal. To be honest, this package is experimental for me and I do not have well-defined plans, but I am open to suggestions.

1. I've implemented custom parser in `0.1.1` version (you can find examples in README), can you take a look, is it something that you had in mind?

2. I never used `ZipFile.jl` or `CodecZLib.jl`, so it would take some time to understand how to use them. One thing that worries me though is that it can strain "autodetection" algorithm too much. The alternative is to add more keyword arguments (like `compress` for example) to override default behavior.

So it will look something like
```julia
# 1
# correct filename, inside data.csv
url = "https://example.com/data.zip"

# `urldownload` guessed from the extension that this is zip archive, unpack it and by investigation of it's content saw `data.csv` file and use default parser 
urldownload(url)

# 2
# incorrect filename, inside data.csv
url = "https://example.com/data.zp"

# `urldownload` ignores autodetection mechanism, just unpack zip archive and use default csv parser
urldownload(url, compress = :ZIP)

# 3
# incorrect filename, inside unknown extension data.cv
url = "https://example.com/data.zp"

# `urldownload` ignores autodetection mechanism, unpack zip archive and use proposed format
urldownload(url, compress = :ZIP, format = :CSV)

# 4
# incorrect filename, custom parser
url = "https://example.com/data.zp"

# `urldownload` ignores autodetection mechanism, unpack zip archive and use custom parser
urldownload(url, compress = :ZIP, parser = custom_parser)

# 5
# incorrect filename, custom parser
url = "https://example.com/data.zp"

# `urldownload` do no try to uncompress the file, just pass data to custom_parser as is, so it's custom_parser duty to unpack and process data
urldownload(url, compress = :NONE, parser = custom_parser)

# 6
# correct filename, custom parser
url = "https://example.com/data.zip"

# `urldownload` guessed compression algorithm, unpack the file and pass data to custom_parser
urldownload(url, parser = custom_parser)
```

**Comment by tbeason** [comment]
It is super easy with CSV.jl, see https://juliadata.github.io/CSV.jl/latest/#Reading-CSV-from-gzip-(.gz)-and-zip-files-1

In the case that it is a single file inside the `.zip` archive, there is no need to know the file name. You would just attempt to parse the file that exists inside, regardless of name. And you could just limit the usage to `.zip` files satisfying this condition (rather than one with 5 `.csv` inside).

Unless you wanted maximum flexibility, I'd probably throw an error if the passed filename was incorrect/not found. But that is perhaps best left for a separate issue as it is not too related to my suggestion.

I will take a look at the custom parser stuff.

**Comment by Arkoniak** [comment]
Thank you for this link! By the way, do you know, `ZipFile` supports only `zip` or `gz` and `tar.gz` files as well?

In the meantime, here is how one can process zip files with custom parser

```julia
using UrlDownload
using ZipFile, CSV, DataFrames

url = "https://raw.githubusercontent.com/Arkoniak/UrlDownload.jl/master/data/ext.csv.zip"
df = urldownload(url, parser = x -> CSV.read(first(ZipFile.Reader(IOBuffer(x)).files)))
 ```

or if you have more than one file

```julia
df = urldownload(url, parser = x -> CSV.read.(ZipFile.Reader(IOBuffer(x)).files))
```

Of course, it's not very convenient to remember, so it should better go to the package itself.

**Comment by tbeason** [comment]
Yea that is pretty much exactly what I had in mind when I asked about custom parsers. It works well!

I'll think about using this package as the backend for some of my packages where I had implemented stuff like this, eg https://github.com/tbeason/FamaFrenchData.jl

**Comment by Arkoniak** [comment]
With #12 merged, compressed data now supported. You can try it with

```julia
import FamaFrenchData
using UrlDownload
const FFD = FamaFrenchData

tbl = "F-F_Research_Data_Factors"

url = FFD.pathtoFamaFrench(tbl)

res = urldownload(url, parser = FFD.parsefile)
```

You can parse more than one file in `zip` archive with the argument `multifiles = true`
```julia
import FamaFrenchData
using UrlDownload
const FFD = FamaFrenchData

tbl = "F-F_Research_Data_Factors"

url = FFD.pathtoFamaFrench(tbl)

res = urldownload(url, parser = FFD.parsefile, multifiles = true)
```
